SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET search_path = public;

CREATE TABLE IF NOT EXISTS socket_types (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cpus (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand            VARCHAR(100) NOT NULL,
  model            VARCHAR(100) NOT NULL,
  socket_id        BIGINT NOT NULL REFERENCES socket_types(id) ON DELETE RESTRICT,
  clock_speed_mhz  INTEGER NOT NULL,
  cores            INTEGER NOT NULL,
  threads          INTEGER NOT NULL,
  tdp_watts        INTEGER NOT NULL,
  price_eur        NUMERIC(10,2) NOT NULL,
  created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_cpus_socket_id ON cpus(socket_id);
CREATE INDEX IF NOT EXISTS idx_cpus_brand_model ON cpus(brand, model);
